Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

src += ['drv_thread.h']

group = DefineGroup('Main', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
