Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
src += ['Reg_Ops.h']
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Tools', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
