#ifndef __DRV_THREAD_H__
#define __DRV_THREAD_H__

#define THREAD_PRIO_MONITOR (1)

#define THREAD_PRIO_ATTICALCU (12)
#define THREAD_PRIO_IMU_DATA_COLLECT (12)
#define THREAD_PRIO_IMU_GYROCALI (12)
#define THREAD_PRIO_RAW_DATA_PROCESS (12)

#define THREAD_PRIO_MOTOR_ATTI_CONTROL (13)
#define THREAD_PRIO_SENSOR_UART_RX (14)
#define THREAD_PRIO_SENSOR_DATA (14)
#define THREAD_PRIO_MOTOR_POS_CONTROL (15)

#define THREAD_PRIO_TEMPCTR (16)
#define THREAD_PRIO_RC_RX (16)
#define THREAD_PRIO_CAN1RX (17)
#define THREAD_PRIO_CAN2RX (17)
#define THREAD_PRIO_RECOIL_FORCE (18)

#define THREAD_PRIO_STATE (22)


#endif
