#ifndef __DRV_THREAD_H__
#define __DRV_THREAD_H__

#define THREAD_PRIO_MONITOR (1)

#define THREAD_PRIO_CAN2RX (5)

#define THREAD_PRIO_AIMBOT_V2_SEND (11)
#define THREAD_PRIO_ATTICALCU (12)

#define THREAD_PRIO_IMU_DATA_COLLECT (12)
#define THREAD_PRIO_IMU_GYROCALI (12)

#define THREAD_PRIO_ALARM (13)
#define THREAD_PRIO_AIMBOT_UART_RX (13)

#define THREAD_PRIO_TEMPCTR (13)
#define THREAD_PRIO_GUNDATA (14)
#define THREAD_PRIO_GIMBALPID (16)
#define THREAD_PRIO_STRIKEPID (17)
#define THREAD_PRIO_ROBOCONTROL (18)
#define THREAD_PRIO_KEYMENU (19)

#define THREAD_PRIO_RC_RX (21)
#define THREAD_PRIO_CAN1RX (22)


#endif
