#ifndef __CUSTOMUI_GRAPHPARAMETERS_H
#define __CUSTOMUI_GRAPHPARAMETERS_H

#include "rtconfig.h"
#define SCOPE_CIRCLE_RADIUS 180 //中心瞄准圆半径大小，所有界面图形的绘制都与它成正比
#define OUTER_SCOPE_CIRCLE_RADIUS 340 //外圈
#define BACKGROUND_LAYER 0      //背景图形图层号
#define DYNAMIC_LAYER 1         //动态图形图层号
#define ANGLE_DIGIT 2           //角度小数点位数
//屏幕中心
#define X_OFFSET 960        
#define Y_OFFSET 540
//超级电容
#define UI_SC_BAR_SIZE             15
#define UI_SC_BAR_CENTER_X     650
#define UI_SC_BAR_CENTER_Y     100
//英雄相机位置辅助
#ifdef CORE_USING_NATION_HERO //国赛老英雄
#define UI_HERO_CREAM_HELP_CENTER_X_1  384
#define UI_HERO_CREAM_HELP_CENTER_Y_1  180
#define UI_HERO_CREAM_HELP_CENTER_X_2  523
#define UI_HERO_CREAM_HELP_CENTER_Y_2  288
#endif
#ifdef CORE_USING_BUNCHES_HERO //双马尾英雄
#define UI_HERO_CREAM_HELP_CENTER_X_1  384
#define UI_HERO_CREAM_HELP_CENTER_Y_1  180
#define UI_HERO_CREAM_HELP_CENTER_X_2  523
#define UI_HERO_CREAM_HELP_CENTER_Y_2  288
#endif
#define UI_STRIKE_MODE_SIZE 8  
#define UI_STRIKE_MODE_CENTER_X     1350
#define UI_STRIKE_MODE_CENTER_Y     100

#define UI_ATTITUDE_ANGLE_COLOR GRAPH_COLOR_GREEN
#define UI_ATTITUDE_ANGLE_SIZE

#define UI_BULLET_SPEED_COLOR GRAPH_COLOR_GREEN
#define UI_BULLET_SPEED_SIZE        12
#define UI_BULLET_SPEED_CENTER_X    1650
#define UI_BULLET_SPEED_CENTER_Y    800

#define UI_REMAIN_AMMO_COLOR GRAPH_COLOR_GREEN
#define UI_REMAIN_AMMO_SIZE 12
#define UI_REMAIN_AMMO_CENTER_X 1650
#define UI_REMAIN_AMMO_CENTER_Y 750

#define UI_MAGAZINE_STATUS_DYN_COLOR    GRAPH_COLOR_CYAN
#define UI_MAGAZINE_STATUS_BKGD_COLOR GRAPH_COLOR_GREEN
#define UI_MAGAZINE_STATUS_SIZE 11
#define UI_MAGAZINE_STATUS_CENTER_X 1650
#define UI_MAGAZINE_STATUS_CENTER_Y 540

#define UI_MOTION_MODE_DYN_COLOR GRAPH_COLOR_CYAN
#define UI_MOTION_MODE_BKGD_COLOR GRAPH_COLOR_GREEN
#define UI_MOTION_MODE_SIZE 11
#define UI_MOTION_MODE_CENTER_X 1650
#define UI_MOTION_MODE_CENTER_Y 570

#define UI_AUXAIM_CROSSHAIR_COLOR GRAPH_COLOR_YELLOW
#define UI_AUXAIM_CROSSHAIR_SIZE  12
#ifdef  CORE_USING_C_BOARD_HERO
#define UI_AUXAIM_CROSSHAIR_X_OFFSET -9
#else
#define UI_AUXAIM_CROSSHAIR_X_OFFSET 0
#endif
#define UI_AUXAIM_BKGD_COLOR GRAPH_COLOR_YELLOW
#define UI_AUXAIM_BKGD_SIZE 40

#define UI_MONITOR_COLOR GRAPH_COLOR_ORANGE
#define UI_MONITOR_SIZE 10
#define UI_MONITOR_CENTER_X 150
#define UI_MONITOR_CENTER_Y 860

#define UI_ENEMY_COLOR GRAPH_COLOR_ORANGE
#define UI_ENEMY_SIZE 20
#define UI_ENEMY_RESERVING_TIME     4000
#define UI_ROTATE_TIPS_COLOR GRAPH_COLOR_ORANGE
#define UI_ROTATE_TIPS_SIZE 20
#define UI_ROTATE_TIPS_CENTER_X 860
#define UI_ROTATE_TIPS_CENTER_Y 800
#define UI_ROTATE_TIPS_RESERVING_TIME 8000

#define UI_WALL_COLOR GRAPH_COLOR_YELLOW
#define UI_WALL_SIZE 40

#define UI_WARNING_COLOR GRAPH_COLOR_ORANGE
#define UI_WARNING_SIZE 16
#define UI_WARNING_CENTER_X 150
#define UI_WARNING_CENTER_Y 650
#define UI_WARNING_RESERVING_TIME   6000

#define UI_LANELINE_COLOR GRAPH_COLOR_ORANGE

#define UI_HEATLIMIT_DYN_COLOR GRAPH_COLOR_CYAN
#define UI_HEATLIMIT_BKGD_COLOR GRAPH_COLOR_GREEN
#define UI_HEATLIMIT_SIZE 11
#define UI_HEATLIMIT_CENTER_X 1650
#define UI_HEATLIMIT_CENTER_Y 600

#define UI_AIMBOT_MODE_DYN_COLOR GRAPH_COLOR_CYAN
#define UI_AIMBOT_MODE_BKGD_COLOR GRAPH_COLOR_GREEN
#define UI_AIMBOT_MODE_SIZE 11
#define UI_AIMBOT_MODE_CENTER_X 1650
#define UI_AIMBOT_MODE_CENTER_Y 480

#define UI_AIMBOT_COLOR_DYN_COLOR GRAPH_COLOR_CYAN
#define UI_AIMBOT_COLOR_BKGD_COLOR GRAPH_COLOR_GREEN
#define UI_AIMBOT_COLOR_SIZE 11
#define UI_AIMBOT_COLOR_CENTER_X 1650
#define UI_AIMBOT_COLOR_CENTER_Y 510

#define UI_OPTION_COLOR GRAPH_COLOR_CYAN
#define UI_OPTION_SIZE 11
#define UI_OPTION_CENTER_X 1610
#define UI_OPTION_CENTER_Y 860

#define UI_VELOCITY_DYN_COLOR GRAPH_COLOR_CYAN
#define UI_VELOCITY_BKGD_COLOR GRAPH_COLOR_GREEN
#define UI_VELOCITY_SIZE 10
#define UI_VELOCITY_CENTER_X 1400
#define UI_VELOCITY_CENTER_Y 450

#define UI_HEIGHT_DYN_COLOR GRAPH_COLOR_CYAN
#define UI_HEIGHT_BKGD_COLOR GRAPH_COLOR_GREEN
#define UI_HEIGHT_SIZE 11
#define UI_HEIGHT_CENTER_X 1650
#define UI_HEIGHT_CENTER_Y 450

#define UI_PITCH_DYN_COLOR GRAPH_COLOR_CYAN
#define UI_PITCH_BKGD_COLOR GRAPH_COLOR_GREEN
#define UI_PITCH_SIZE 15
#define UI_ABS_PITCH_CENTER_X 1200
#define UI_ABS_PITCH_CENTER_Y 450
#define UI_RELAT_PITCH_CENTER_X 1200
#define UI_RELAT_PITCH_CENTER_Y 430
#endif
