from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
src += ['CustomUI_GraphParameters.h']

CPPPATH = [cwd]

group = DefineGroup('UI', src, depend = [''], CPPPATH = CPPPATH)

Return('group')