from building import *

cwd = GetCurrentDir()
src = Glob('*.h')
src += Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('User\MAVLINK', src, depend = [''], CPPPATH = CPPPATH)
objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('group')

# for module compiling
#import os
#from building import *

#cwd = GetCurrentDir()
#objs = []
#list = os.listdir(cwd)

#for d in list:
#    path = os.path.join(cwd, d)
#    if os.path.isfile(os.path.join(path, 'SConscript')):
#        objs = objs + SConscript(os.path.join(d, 'SConscript'))

#Return('objs')
